### PR TITLE
Featured branch

### PR DESCRIPTION
**Pull request by nyatindopatrick**
The Smashing Magazine Heat-map

### CODE REVIEW

**Review by fatymahmed — COMMENTED** [review]
## Hi @nyatindopatrick @kelibst,
Great job guys 👏👏, However, there are a few things that you need to fix.

**3 articles rows**
- Your website should contain 3 articles, each takes one-third of the width.

**Each article**
- It uses `<article>` tag [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/design_teardown/article_requirement.png)

**Footer**
- Your footer should contain centered links just like in the smashing webpage.

****
- Remove this part _This is an example of how you may give instructions on setting up your project locally..._ from your README. (It's a guide instruction for a readme but should not be in your readme file).

- Files not related to the project should not be committed and added to .gitignore (e.g. .DS_Store), kindly remove the DS_Store. [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png).

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Kindly make the suggested changes and request for another code review.
### Status: Changes Required
_Feel free to reach out to me on slack (Fatima) if you have any questions, I'd be happy to help._

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Wonderful job team! :clap: 
The effort you put into this is showing! Please consider using the `article` tag to wrap each article on the page as opposed to the `div` tag as @fatymahmed rightly pointed out. This is a hard requirement and is currently the only visible thing I can see holding this project back from an approval. Please make the change and submit for another review.

#### Use of article tags
* It uses `<article>` tag [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/design_teardown/article_requirement.png)

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by rOluochKe — APPROVED** [review]
Hello @nyatindopatrick and @kelibst 

### Following previous reviews and having seen you have made all the changes required, I, therefore, approve of your project. 

### Congratulations :clap: :boom:

### You can merge and submit a project completion form from your dashboard.
- You can move on to the next project. Happy coding!

**Pull request merged**
